# Build Configuration
[build]
publish = "public"
command = "npm run build"

# Environment Configuration
[build.environment]
NODE_VERSION = "16"

# Environment plugin to allow for contextual env variables.
# https://github.com/cball/netlify-plugin-contextual-env
[[plugins]]
package = "netlify-plugin-contextual-env"
[plugins.inputs]
mode = 'prefix'

# Adding GNU Terry Pratchett Header
[[headers]]
for = "/*"
[headers.values]
X-Clacks-Overhead = "GNU Terry Pratchett"
