# fly.toml file generated for cms-benryder-me on 2023-04-07T12:32:35+01:00

app = "cms-benryder-me"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
    source="cms_benryder_me_vol"
    destination="/uploads"
